source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "2.6.2"

gem "dotenv"
gem "httparty"

git "https://github.com/pakyow/pakyow.git", glob: "**/*.gemspec" do
  gem "pakyow-core"
  gem "pakyow-support"
  gem "pakyow-routing"
end

group :development do
  # Speed up project boot time.
  #
  gem "bootsnap", require: false

  # Use SQLite3 as the default data source in development.
  #
  gem "sqlite3"
end
